# Generated by Selenium IDE
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestTest1():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_test1(self):
    self.driver.get("https://my.replika.ai/login")
    self.driver.set_window_size(1470, 919)
    self.driver.find_element(By.ID, "login-email").click()
    self.driver.find_element(By.ID, "login-email").send_keys("farazuddin.m1999@gmail.com")
    self.driver.find_element(By.ID, "login-password").click()
    self.driver.find_element(By.ID, "login-password").send_keys("hussnafarha1")
    self.driver.find_element(By.CSS_SELECTOR, ".iubenda-cs-accept-btn").click()
    self.driver.find_element(By.CSS_SELECTOR, ".AuthLayout__SubmitButton-sc-110rp2i-17").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".DialogLayout__StyledCloseIcon-sc-103t4c8-4").click()
    self.driver.execute_script("window.scrollTo(0,0)")
    self.driver.find_element(By.CSS_SELECTOR, ".DialogLayout__CancelButton-sc-103t4c8-13").click()
  
